Fixed: Exceptions of type RecoverableUserCallbackError, raised in 
callbacks `solve_with_jacobian` and 
`solve_with_jacobian_and_track_n_linear_iterations` of the 
TrilinosWrappers::NOXSolver class, are now treated as "recoverable",
if the NOX parameter "Newton/Rescue Bad Newton Solve" is set to `true`,
which is, in fact, its default value. Exceptions of all other types and 
also all exceptions raised in other callbacks are still treated as 
"irrecoverable".
<br>
(Vladimir Ivannikov, 2023/12/26)
